#### Pivot Pandas

In [4]:
import pandas as pd

data = {
    "City": ["New York", "New York", "New York", "Los Angeles", "Los Angeles",
             "Los Angeles", "Chicago", "Chicago", "Chicago", "Houston",
             "Houston", "Houston", "Miami", "Miami", "Miami",
             "Dallas", "Dallas", "Dallas", "Seattle", "Seattle"],
    
    "Date": pd.to_datetime(["2024-02-01", "2024-02-02", "2024-02-03", "2024-02-04", "2024-02-05",
                            "2024-02-06", "2024-02-07", "2024-02-08", "2024-02-09", "2024-02-10",
                            "2024-02-11", "2024-02-12", "2024-02-13", "2024-02-14", "2024-02-15",
                            "2024-02-16", "2024-02-17", "2024-02-18", "2024-02-19", "2024-02-20"]),
    
    "Product": ["Laptop", "Smartphone", "Tablet", "Laptop", "Smartwatch",
                "Tablet", "Headphones", "Laptop", "Smartphone", "Tablet",
                "Smartwatch", "Laptop", "Smartphone", "Tablet", "Headphones",
                "Smartwatch", "Laptop", "Smartphone", "Tablet", "Smartwatch"],
    
    "Sales": [1520, 980, 1350, 750, 1780, 2100, 890, 1250, 670, 1900,
              1200, 1100, 1300, 780, 1650, 2050, 920, 1400, 720, 1850],
    
    "Profit": [300, 120, 250, 90, 400, 500, 130, 270, 80, 420,
               210, 190, 230, 100, 370, 480, 150, 260, 95, 410]
}

df = pd.DataFrame(data)
print(df)

           City       Date     Product  Sales  Profit
0      New York 2024-02-01      Laptop   1520     300
1      New York 2024-02-02  Smartphone    980     120
2      New York 2024-02-03      Tablet   1350     250
3   Los Angeles 2024-02-04      Laptop    750      90
4   Los Angeles 2024-02-05  Smartwatch   1780     400
5   Los Angeles 2024-02-06      Tablet   2100     500
6       Chicago 2024-02-07  Headphones    890     130
7       Chicago 2024-02-08      Laptop   1250     270
8       Chicago 2024-02-09  Smartphone    670      80
9       Houston 2024-02-10      Tablet   1900     420
10      Houston 2024-02-11  Smartwatch   1200     210
11      Houston 2024-02-12      Laptop   1100     190
12        Miami 2024-02-13  Smartphone   1300     230
13        Miami 2024-02-14      Tablet    780     100
14        Miami 2024-02-15  Headphones   1650     370
15       Dallas 2024-02-16  Smartwatch   2050     480
16       Dallas 2024-02-17      Laptop    920     150
17       Dallas 2024-02-18  Smartphone   1400     260
18      Seattle 2024-02-19      Tablet    720      95
19      Seattle 2024-02-20  Smartwatch   1850     410

1. How would you create a pivot table to show Sales for each City on each Date using the sample DataFrame?

In [10]:
df.pivot(index="Date", columns="City", values="Sales").fillna(0)

City        Chicago  Dallas  Houston  Los Angeles   Miami  New York  Seattle
Date
2024-02-01      0.0     0.0      0.0          0.0     0.0    1520.0      0.0
2024-02-02      0.0     0.0      0.0          0.0     0.0     980.0      0.0
2024-02-03      0.0     0.0      0.0          0.0     0.0    1350.0      0.0
2024-02-04      0.0     0.0      0.0        750.0     0.0       0.0      0.0
2024-02-05      0.0     0.0      0.0       1780.0     0.0       0.0      0.0
2024-02-06      0.0     0.0      0.0       2100.0     0.0       0.0      0.0
2024-02-07    890.0     0.0      0.0          0.0     0.0       0.0      0.0
2024-02-08   1250.0     0.0      0.0          0.0     0.0       0.0      0.0
2024-02-09    670.0     0.0      0.0          0.0     0.0       0.0      0.0
2024-02-10      0.0     0.0   1900.0          0.0     0.0       0.0      0.0
2024-02-11      0.0     0.0   1200.0          0.0     0.0       0.0      0.0
2024-02-12      0.0     0.0   1100.0          0.0     0.0       0.0      0.0
2024-02-13      0.0     0.0      0.0          0.0  1300.0       0.0      0.0
2024-02-14      0.0     0.0      0.0          0.0   780.0       0.0      0.0
2024-02-15      0.0     0.0      0.0          0.0  1650.0       0.0      0.0
2024-02-16      0.0  2050.0      0.0          0.0     0.0       0.0      0.0
2024-02-17      0.0   920.0      0.0          0.0     0.0       0.0      0.0
2024-02-18      0.0  1400.0      0.0          0.0     0.0       0.0      0.0
2024-02-19      0.0     0.0      0.0          0.0     0.0       0.0    720.0
2024-02-20      0.0     0.0      0.0          0.0     0.0       0.0   1850.0

2. How can you pivot the DataFrame to show both Sales and Profit for each City on each Date?

In [12]:
df.pivot(index="City", columns="Date", values=["Sales", "Profit"]).fillna(0)

                 Sales                                                         \
Date        2024-02-01 2024-02-02 2024-02-03 2024-02-04 2024-02-05 2024-02-06
City
Chicago            0.0        0.0        0.0        0.0        0.0        0.0
Dallas             0.0        0.0        0.0        0.0        0.0        0.0
Houston            0.0        0.0        0.0        0.0        0.0        0.0
Los Angeles        0.0        0.0        0.0      750.0     1780.0     2100.0
Miami              0.0        0.0        0.0        0.0        0.0        0.0
New York        1520.0      980.0     1350.0        0.0        0.0        0.0
Seattle            0.0        0.0        0.0        0.0        0.0        0.0

                                                         ...     Profit  \
Date        2024-02-07 2024-02-08 2024-02-09 2024-02-10  ... 2024-02-11
City                                                     ...
Chicago          890.0     1250.0      670.0        0.0  ...        0.0
Dallas             0.0        0.0        0.0        0.0  ...        0.0
Houston            0.0        0.0        0.0     1900.0  ...      210.0
Los Angeles        0.0        0.0        0.0        0.0  ...        0.0
Miami              0.0        0.0        0.0        0.0  ...        0.0
New York           0.0        0.0        0.0        0.0  ...        0.0
Seattle            0.0        0.0        0.0        0.0  ...        0.0

                                                                               \
Date        2024-02-12 2024-02-13 2024-02-14 2024-02-15 2024-02-16 2024-02-17
City
Chicago            0.0        0.0        0.0        0.0        0.0        0.0
Dallas             0.0        0.0        0.0        0.0      480.0      150.0
Houston          190.0        0.0        0.0        0.0        0.0        0.0
Los Angeles        0.0        0.0        0.0        0.0        0.0        0.0
Miami              0.0      230.0      100.0      370.0        0.0        0.0
New York           0.0        0.0        0.0        0.0        0.0        0.0
Seattle            0.0        0.0        0.0        0.0        0.0        0.0


Date        2024-02-18 2024-02-19 2024-02-20
City
Chicago            0.0        0.0        0.0
Dallas           260.0        0.0        0.0
Houston            0.0        0.0        0.0
Los Angeles        0.0        0.0        0.0
Miami              0.0        0.0        0.0
New York           0.0        0.0        0.0
Seattle            0.0       95.0      410.0

[7 rows x 40 columns]

3. How would you pivot the DataFrame to have Date and Product as the index, City as columns, and Sales as values?

In [13]:
df.pivot(index=["Date", "Product"], columns="City", values="Sales").fillna(0)

,City,Chicago,Dallas,Houston,Los Angeles,Miami,New York,Seattle
Date,Product,,,,,,,
2024-02-01,Laptop,0.0,0.0,0.0,0.0,0.0,1520.0,0.0
2024-02-02,Smartphone,0.0,0.0,0.0,0.0,0.0,980.0,0.0
2024-02-03,Tablet,0.0,0.0,0.0,0.0,0.0,1350.0,0.0
2024-02-04,Laptop,0.0,0.0,0.0,750.0,0.0,0.0,0.0
2024-02-05,Smartwatch,0.0,0.0,0.0,1780.0,0.0,0.0,0.0
2024-02-06,Tablet,0.0,0.0,0.0,2100.0,0.0,0.0,0.0
2024-02-07,Headphones,890.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-02-08,Laptop,1250.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-02-09,Smartphone,670.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-02-10,Tablet,0.0,0.0,1900.0,0.0,0.0,0.0,0.0
2024-02-11,Smartwatch,0.0,0.0,1200.0,0.0,0.0,0.0,0.0
2024-02-12,Laptop,0.0,0.0,1100.0,0.0,0.0,0.0,0.0
2024-02-13,Smartphone,0.0,0.0,0.0,0.0,1300.0,0.0,0.0
2024-02-14,Tablet,0.0,0.0,0.0,0.0,780.0,0.0,0.0
2024-02-15,Headphones,0.0,0.0,0.0,0.0,1650.0,0.0,0.0
2024-02-16,Smartwatch,0.0,2050.0,0.0,0.0,0.0,0.0,0.0
2024-02-17,Laptop,0.0,920.0,0.0,0.0,0.0,0.0,0.0
2024-02-18,Smartphone,0.0,1400.0,0.0,0.0,0.0,0.0,0.0
2024-02-19,Tablet,0.0,0.0,0.0,0.0,0.0,0.0,720.0
2024-02-20,Smartwatch,0.0,0.0,0.0,0.0,0.0,0.0,1850.0

4. How can you use pivot_table to calculate the average Sales for each Product in each City?

In [22]:
df.pivot_table(index="Product", columns="City", values="Sales", aggfunc="mean", margins=True, margins_name="Total").fillna(0)

City,Chicago,Dallas,Houston,Los Angeles,Miami,New York,Seattle,Total
Product,,,,,,,,
Headphones,890.000000,0.000000,0.0,0.000000,1650.000000,0.000000,0.0,1270.0
Laptop,1250.000000,920.000000,1100.0,750.000000,0.000000,1520.000000,0.0,1108.0
Smartphone,670.000000,1400.000000,0.0,0.000000,1300.000000,980.000000,0.0,1087.5
Smartwatch,0.000000,2050.000000,1200.0,1780.000000,0.000000,0.000000,1850.0,1720.0
Tablet,0.000000,0.000000,1900.0,2100.000000,780.000000,1350.000000,720.0,1370.0
Total,936.666667,1456.666667,1400.0,1543.333333,1243.333333,1283.333333,1285.0,1308.0

5. Given the sample DataFrame, how would you pivot it to show the count of Product sold in each City on each Date?

6. How can you fill missing values with 0 in a pivot table created from the sample DataFrame?

7. If the DataFrame had duplicate entries for Date and City, how can you use pivot_table to handle this by calculating the sum of Sales?

8. How can you perform both mean and sum aggregations on Sales for each Product in each City?

9. How can you create a pivot table with a MultiIndex on both the rows (Date, Product) and columns (City)?

10. How can you add a total row and column to a pivot table showing Sales for each City on each Date?

11. How would you create a pivot table to show monthly Sales for each Product given the Date column includes multiple months?

12. How would you pivot the DataFrame to compare the average Profit across different Cities?

13. How can you create a pivot table to show the count of Sales transactions for each Product segmented by City?

14. How can you prepare the DataFrame for a heatmap visualization by pivoting City, Date, and Sales to have City as rows and Date as columns?

15. How can you use a custom aggregation function (e.g., lambda x: x.max() - x.min()) in a pivot table to calculate the range of Sales for each Product in each
City?