#### Pivot Pandas

In [141]:
import pandas as pd

In [142]:
data = {
    "City": ["New York", "New York", "New York", "Los Angeles", "Los Angeles",
             "Los Angeles", "Chicago", "Chicago", "Chicago", "Houston",
             "Houston", "Houston", "Miami", "Miami", "Miami",
             "Dallas", "Dallas", "Dallas", "Seattle", "Seattle"],
    
    "Date": pd.to_datetime(["2024-02-01", "2024-02-02", "2024-02-03", "2024-02-04", "2024-02-05",
                            "2024-02-06", "2024-02-07", "2024-02-08", "2024-02-09", "2024-02-10",
                            "2024-02-11", "2024-02-12", "2024-02-13", "2024-02-14", "2024-02-15",
                            "2024-02-16", "2024-02-17", "2024-02-18", "2024-02-19", "2024-02-20"]),
    
    "Product": ["Laptop", "Smartphone", "Tablet", "Laptop", "Smartwatch",
                "Tablet", "Headphones", "Laptop", "Smartphone", "Tablet",
                "Smartwatch", "Laptop", "Smartphone", "Tablet", "Headphones",
                "Smartwatch", "Laptop", "Smartphone", "Tablet", "Smartwatch"],
    
    "Sales": [1520, 980, 1350, 750, 1780, 2100, 890, 1250, 670, 1900,
              1200, 1100, 1300, 780, 1650, 2050, 920, 1400, 720, 1850],
    
    "Profit": [300, 120, 250, 90, 400, 500, 130, 270, 80, 420,
               210, 190, 230, 100, 370, 480, 150, 260, 95, 410]
}

df = pd.DataFrame(data)
print(df.head(10))

          City       Date     Product  Sales  Profit
0     New York 2024-02-01      Laptop   1520     300
1     New York 2024-02-02  Smartphone    980     120
2     New York 2024-02-03      Tablet   1350     250
3  Los Angeles 2024-02-04      Laptop    750      90
4  Los Angeles 2024-02-05  Smartwatch   1780     400
5  Los Angeles 2024-02-06      Tablet   2100     500
6      Chicago 2024-02-07  Headphones    890     130
7      Chicago 2024-02-08      Laptop   1250     270
8      Chicago 2024-02-09  Smartphone    670      80
9      Houston 2024-02-10      Tablet   1900     420

1. How would you create a pivot table to show Sales for each City on each Date using the sample DataFrame?

In [143]:
df.pivot(index="Date", columns="City", values="Sales").fillna(0)

City        Chicago  Dallas  Houston  Los Angeles   Miami  New York  Seattle
Date
2024-02-01      0.0     0.0      0.0          0.0     0.0    1520.0      0.0
2024-02-02      0.0     0.0      0.0          0.0     0.0     980.0      0.0
2024-02-03      0.0     0.0      0.0          0.0     0.0    1350.0      0.0
2024-02-04      0.0     0.0      0.0        750.0     0.0       0.0      0.0
2024-02-05      0.0     0.0      0.0       1780.0     0.0       0.0      0.0
2024-02-06      0.0     0.0      0.0       2100.0     0.0       0.0      0.0
2024-02-07    890.0     0.0      0.0          0.0     0.0       0.0      0.0
2024-02-08   1250.0     0.0      0.0          0.0     0.0       0.0      0.0
2024-02-09    670.0     0.0      0.0          0.0     0.0       0.0      0.0
2024-02-10      0.0     0.0   1900.0          0.0     0.0       0.0      0.0
2024-02-11      0.0     0.0   1200.0          0.0     0.0       0.0      0.0
2024-02-12      0.0     0.0   1100.0          0.0     0.0       0.0      0.0
2024-02-13      0.0     0.0      0.0          0.0  1300.0       0.0      0.0
2024-02-14      0.0     0.0      0.0          0.0   780.0       0.0      0.0
2024-02-15      0.0     0.0      0.0          0.0  1650.0       0.0      0.0
2024-02-16      0.0  2050.0      0.0          0.0     0.0       0.0      0.0
2024-02-17      0.0   920.0      0.0          0.0     0.0       0.0      0.0
2024-02-18      0.0  1400.0      0.0          0.0     0.0       0.0      0.0
2024-02-19      0.0     0.0      0.0          0.0     0.0       0.0    720.0
2024-02-20      0.0     0.0      0.0          0.0     0.0       0.0   1850.0

2. How can you pivot the DataFrame to show both Sales and Profit for each City on each Date?

In [144]:
df.pivot(index="City", columns="Date", values=["Sales", "Profit"]).fillna(0)

                 Sales                                                         \
Date        2024-02-01 2024-02-02 2024-02-03 2024-02-04 2024-02-05 2024-02-06
City
Chicago            0.0        0.0        0.0        0.0        0.0        0.0
Dallas             0.0        0.0        0.0        0.0        0.0        0.0
Houston            0.0        0.0        0.0        0.0        0.0        0.0
Los Angeles        0.0        0.0        0.0      750.0     1780.0     2100.0
Miami              0.0        0.0        0.0        0.0        0.0        0.0
New York        1520.0      980.0     1350.0        0.0        0.0        0.0
Seattle            0.0        0.0        0.0        0.0        0.0        0.0

                                                         ...     Profit  \
Date        2024-02-07 2024-02-08 2024-02-09 2024-02-10  ... 2024-02-11
City                                                     ...
Chicago          890.0     1250.0      670.0        0.0  ...        0.0
Dallas             0.0        0.0        0.0        0.0  ...        0.0
Houston            0.0        0.0        0.0     1900.0  ...      210.0
Los Angeles        0.0        0.0        0.0        0.0  ...        0.0
Miami              0.0        0.0        0.0        0.0  ...        0.0
New York           0.0        0.0        0.0        0.0  ...        0.0
Seattle            0.0        0.0        0.0        0.0  ...        0.0

                                                                               \
Date        2024-02-12 2024-02-13 2024-02-14 2024-02-15 2024-02-16 2024-02-17
City
Chicago            0.0        0.0        0.0        0.0        0.0        0.0
Dallas             0.0        0.0        0.0        0.0      480.0      150.0
Houston          190.0        0.0        0.0        0.0        0.0        0.0
Los Angeles        0.0        0.0        0.0        0.0        0.0        0.0
Miami              0.0      230.0      100.0      370.0        0.0        0.0
New York           0.0        0.0        0.0        0.0        0.0        0.0
Seattle            0.0        0.0        0.0        0.0        0.0        0.0


Date        2024-02-18 2024-02-19 2024-02-20
City
Chicago            0.0        0.0        0.0
Dallas           260.0        0.0        0.0
Houston            0.0        0.0        0.0
Los Angeles        0.0        0.0        0.0
Miami              0.0        0.0        0.0
New York           0.0        0.0        0.0
Seattle            0.0       95.0      410.0

[7 rows x 40 columns]

3. How would you pivot the DataFrame to have Date and Product as the index, City as columns, and Sales as values?

In [145]:
df.pivot(index=["Date", "Product"], columns="City", values="Sales").fillna(0)

,City,Chicago,Dallas,Houston,Los Angeles,Miami,New York,Seattle
Date,Product,,,,,,,
2024-02-01,Laptop,0.0,0.0,0.0,0.0,0.0,1520.0,0.0
2024-02-02,Smartphone,0.0,0.0,0.0,0.0,0.0,980.0,0.0
2024-02-03,Tablet,0.0,0.0,0.0,0.0,0.0,1350.0,0.0
2024-02-04,Laptop,0.0,0.0,0.0,750.0,0.0,0.0,0.0
2024-02-05,Smartwatch,0.0,0.0,0.0,1780.0,0.0,0.0,0.0
2024-02-06,Tablet,0.0,0.0,0.0,2100.0,0.0,0.0,0.0
2024-02-07,Headphones,890.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-02-08,Laptop,1250.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-02-09,Smartphone,670.0,0.0,0.0,0.0,0.0,0.0,0.0
2024-02-10,Tablet,0.0,0.0,1900.0,0.0,0.0,0.0,0.0
2024-02-11,Smartwatch,0.0,0.0,1200.0,0.0,0.0,0.0,0.0
2024-02-12,Laptop,0.0,0.0,1100.0,0.0,0.0,0.0,0.0
2024-02-13,Smartphone,0.0,0.0,0.0,0.0,1300.0,0.0,0.0
2024-02-14,Tablet,0.0,0.0,0.0,0.0,780.0,0.0,0.0
2024-02-15,Headphones,0.0,0.0,0.0,0.0,1650.0,0.0,0.0
2024-02-16,Smartwatch,0.0,2050.0,0.0,0.0,0.0,0.0,0.0
2024-02-17,Laptop,0.0,920.0,0.0,0.0,0.0,0.0,0.0
2024-02-18,Smartphone,0.0,1400.0,0.0,0.0,0.0,0.0,0.0
2024-02-19,Tablet,0.0,0.0,0.0,0.0,0.0,0.0,720.0
2024-02-20,Smartwatch,0.0,0.0,0.0,0.0,0.0,0.0,1850.0

4. How can you use pivot_table to calculate the average Sales for each Product in each City?

In [146]:
df.pivot_table(index="Product", columns="City", values="Sales", aggfunc="mean", margins=True, margins_name="Total").fillna(0)

City,Chicago,Dallas,Houston,Los Angeles,Miami,New York,Seattle,Total
Product,,,,,,,,
Headphones,890.000000,0.000000,0.0,0.000000,1650.000000,0.000000,0.0,1270.0
Laptop,1250.000000,920.000000,1100.0,750.000000,0.000000,1520.000000,0.0,1108.0
Smartphone,670.000000,1400.000000,0.0,0.000000,1300.000000,980.000000,0.0,1087.5
Smartwatch,0.000000,2050.000000,1200.0,1780.000000,0.000000,0.000000,1850.0,1720.0
Tablet,0.000000,0.000000,1900.0,2100.000000,780.000000,1350.000000,720.0,1370.0
Total,936.666667,1456.666667,1400.0,1543.333333,1243.333333,1283.333333,1285.0,1308.0

In [ ]:
data = {
    "City": [
        "New York", "New York", "New York", "New York", "New York", "Los Angeles", "Los Angeles", "Los Angeles", "Los Angeles", "Los Angeles",
        "Chicago", "Chicago", "Chicago", "Chicago", "Chicago", "Houston", "Houston", "Houston", "Houston", "Houston",
        "Miami", "Miami", "Miami", "Miami", "Miami", "Dallas", "Dallas", "Dallas", "Dallas", "Dallas",
        "New York", "New York", "New York", "New York", "New York", "Los Angeles", "Los Angeles", "Los Angeles", "Los Angeles", "Los Angeles",
        "Chicago", "Chicago", "Chicago", "Chicago", "Chicago", "Houston", "Houston", "Houston", "Houston", "Houston"
    ],
    "Date": pd.to_datetime([
        "2024-02-01", "2024-02-01", "2024-02-01", "2024-02-02", "2024-02-02", "2024-02-02", "2024-02-03", "2024-02-03", "2024-02-03", "2024-02-04",
        "2024-02-04", "2024-02-04", "2024-02-05", "2024-02-05", "2024-02-05", "2024-02-06", "2024-02-06", "2024-02-06", "2024-02-07", "2024-02-07",
        "2024-02-07", "2024-02-01", "2024-02-01", "2024-02-01", "2024-02-02", "2024-02-02", "2024-02-02", "2024-02-03", "2024-02-03", "2024-02-03",
        "2024-02-04", "2024-02-04", "2024-02-04", "2024-02-05", "2024-02-05", "2024-02-05", "2024-02-06", "2024-02-06", "2024-02-06", "2024-02-07",
        "2024-02-07", "2024-02-07", "2024-02-01", "2024-02-01", "2024-02-01", "2024-02-02", "2024-02-02", "2024-02-02", "2024-02-03", "2024-02-03"
    ]),
    "Product": [
        "Laptop", "Laptop", "Smartphone", "Smartphone", "Tablet", "Tablet", "Headphones", "Headphones", "Smartwatch", "Smartwatch",
        "Laptop", "Laptop", "Smartphone", "Smartphone", "Tablet", "Tablet", "Headphones", "Headphones", "Smartwatch", "Smartwatch",
        "Laptop", "Laptop", "Smartphone", "Smartphone", "Tablet", "Tablet", "Headphones", "Headphones", "Smartwatch", "Smartwatch",
        "Laptop", "Laptop", "Smartphone", "Smartphone", "Tablet", "Tablet", "Headphones", "Headphones", "Smartwatch", "Smartwatch",
        "Laptop", "Laptop", "Smartphone", "Smartphone", "Tablet", "Tablet", "Headphones", "Headphones", "Smartwatch", "Smartwatch"
    ],
    "Sales": [
        15, 14, 10, 10, 13, 11, 7, 8, 18, 15, 21, 20, 9, 9, 12, 13, 7, 7, 19, 18,12, 11, 13, 12, 8, 8, 16, 
        16, 20, 19, 9, 10, 14, 13, 7, 7, 18, 18, 15, 14, 10, 9, 13, 13, 7, 7, 18, 16, 21, 20
    ],
    "Profit": [
        30000, 28000, 12000, 14000, 25000, 20000, 9000, 10000, 40000, 35000, 50000, 48000, 13000, 15000, 27000, 25000, 8000, 9500,
        42000, 39000, 21000, 19000, 23000, 22000, 10000, 12000, 37000, 35000, 48000, 46000, 15000, 14000, 26000, 24000, 9500, 
        10000, 41000, 39000, 30000, 28000, 12000, 11000, 25000, 23000, 9000, 8500, 40000, 38000, 50000, 48000
    ]
}
df = pd.DataFrame(data)
print(df.head(10))

          City       Date     Product  Sales  Profit
0     New York 2024-02-01      Laptop     15   30000
1     New York 2024-02-01      Laptop     14   28000
2     New York 2024-02-01  Smartphone     10   12000
3     New York 2024-02-02  Smartphone     10   14000
4     New York 2024-02-02      Tablet     13   25000
5  Los Angeles 2024-02-02      Tablet     11   20000
6  Los Angeles 2024-02-03  Headphones      7    9000
7  Los Angeles 2024-02-03  Headphones      8   10000
8  Los Angeles 2024-02-03  Smartwatch     18   40000
9  Los Angeles 2024-02-04  Smartwatch     15   35000

5. Given the sample DataFrame, how would you pivot it to show the count of Product sold in each City on each Date?

In [148]:
df.pivot_table(index=["Product", "Date"], columns="City", values="Sales", aggfunc="sum").fillna(0)

City                   Chicago  Dallas  Houston  Los Angeles  Miami  New York
Product    Date
Headphones 2024-02-02      0.0    16.0     34.0          0.0    0.0       0.0
           2024-02-03      0.0    16.0      0.0         15.0    0.0       0.0
           2024-02-06      0.0     0.0     14.0         36.0    0.0       0.0
Laptop     2024-02-01      0.0     0.0      0.0          0.0   11.0      29.0
           2024-02-04     41.0     0.0      0.0          0.0    0.0      19.0
           2024-02-07     19.0     0.0      0.0          0.0   12.0       0.0
Smartphone 2024-02-01     26.0     0.0      0.0          0.0   25.0      10.0
           2024-02-02      0.0     0.0      0.0          0.0    0.0      10.0
           2024-02-04      0.0     0.0      0.0          0.0    0.0      14.0
           2024-02-05     18.0     0.0      0.0          0.0    0.0      13.0
Smartwatch 2024-02-03      0.0    39.0     41.0         18.0    0.0       0.0
           2024-02-04      0.0     0.0      0.0         15.0    0.0       0.0
           2024-02-06      0.0     0.0      0.0         15.0    0.0       0.0
           2024-02-07      0.0     0.0     37.0         14.0    0.0       0.0
Tablet     2024-02-01      7.0     0.0      0.0          0.0    0.0       0.0
           2024-02-02      0.0     8.0      7.0         11.0    8.0      13.0
           2024-02-05     12.0     0.0      0.0          7.0    0.0       7.0
           2024-02-06      0.0     0.0     13.0          0.0    0.0       0.0

6. How can you fill missing values with 0 in a pivot table created from the sample DataFrame?

In [149]:
# We can use "fillna(0)" to fill missing values with 0.

df.pivot_table(index=["Product", "Date"], columns="City", values="Sales", aggfunc="count").fillna(0)

City                   Chicago  Dallas  Houston  Los Angeles  Miami  New York
Product    Date
Headphones 2024-02-02      0.0     1.0      2.0          0.0    0.0       0.0
           2024-02-03      0.0     1.0      0.0          2.0    0.0       0.0
           2024-02-06      0.0     0.0      2.0          2.0    0.0       0.0
Laptop     2024-02-01      0.0     0.0      0.0          0.0    1.0       2.0
           2024-02-04      2.0     0.0      0.0          0.0    0.0       2.0
           2024-02-07      2.0     0.0      0.0          0.0    1.0       0.0
Smartphone 2024-02-01      2.0     0.0      0.0          0.0    2.0       1.0
           2024-02-02      0.0     0.0      0.0          0.0    0.0       1.0
           2024-02-04      0.0     0.0      0.0          0.0    0.0       1.0
           2024-02-05      2.0     0.0      0.0          0.0    0.0       1.0
Smartwatch 2024-02-03      0.0     2.0      2.0          1.0    0.0       0.0
           2024-02-04      0.0     0.0      0.0          1.0    0.0       0.0
           2024-02-06      0.0     0.0      0.0          1.0    0.0       0.0
           2024-02-07      0.0     0.0      2.0          1.0    0.0       0.0
Tablet     2024-02-01      1.0     0.0      0.0          0.0    0.0       0.0
           2024-02-02      0.0     1.0      1.0          1.0    1.0       1.0
           2024-02-05      1.0     0.0      0.0          1.0    0.0       1.0
           2024-02-06      0.0     0.0      1.0          0.0    0.0       0.0

7. If the DataFrame had duplicate entries for Date and City, how can you use pivot_table to handle this by calculating the sum of Sales?

In [150]:
# The parameter "aggfunc" will aggregate the duplicates to the mentioned methond such as sum in this case.
df.pivot_table(index=["Product", "Date"], columns="City", values="Sales", aggfunc="sum").fillna(0)

City                   Chicago  Dallas  Houston  Los Angeles  Miami  New York
Product    Date
Headphones 2024-02-02      0.0    16.0     34.0          0.0    0.0       0.0
           2024-02-03      0.0    16.0      0.0         15.0    0.0       0.0
           2024-02-06      0.0     0.0     14.0         36.0    0.0       0.0
Laptop     2024-02-01      0.0     0.0      0.0          0.0   11.0      29.0
           2024-02-04     41.0     0.0      0.0          0.0    0.0      19.0
           2024-02-07     19.0     0.0      0.0          0.0   12.0       0.0
Smartphone 2024-02-01     26.0     0.0      0.0          0.0   25.0      10.0
           2024-02-02      0.0     0.0      0.0          0.0    0.0      10.0
           2024-02-04      0.0     0.0      0.0          0.0    0.0      14.0
           2024-02-05     18.0     0.0      0.0          0.0    0.0      13.0
Smartwatch 2024-02-03      0.0    39.0     41.0         18.0    0.0       0.0
           2024-02-04      0.0     0.0      0.0         15.0    0.0       0.0
           2024-02-06      0.0     0.0      0.0         15.0    0.0       0.0
           2024-02-07      0.0     0.0     37.0         14.0    0.0       0.0
Tablet     2024-02-01      7.0     0.0      0.0          0.0    0.0       0.0
           2024-02-02      0.0     8.0      7.0         11.0    8.0      13.0
           2024-02-05     12.0     0.0      0.0          7.0    0.0       7.0
           2024-02-06      0.0     0.0     13.0          0.0    0.0       0.0

8. How can you perform both mean and sum aggregations on Sales for each Product in each City?

In [151]:
df.pivot_table(index="City", columns="Product", values="Sales",aggfunc=["mean", "sum"]).fillna(0)

                  mean                                            sum         \
Product     Headphones Laptop Smartphone Smartwatch Tablet Headphones Laptop
City
Chicago           0.00   15.0      11.00        0.0    9.5        0.0   60.0
Dallas           16.00    0.0       0.00       19.5    8.0       32.0    0.0
Houston          12.00    0.0       0.00       19.5   10.0       48.0    0.0
Los Angeles      12.75    0.0       0.00       15.5    9.0       51.0    0.0
Miami             0.00   11.5      12.50        0.0    8.0        0.0   23.0
New York          0.00   12.0      11.75        0.0   10.0        0.0   48.0


Product     Smartphone Smartwatch Tablet
City
Chicago           44.0        0.0   19.0
Dallas             0.0       39.0    8.0
Houston            0.0       78.0   20.0
Los Angeles        0.0       62.0   18.0
Miami             25.0        0.0    8.0
New York          47.0        0.0   20.0

9. How can you create a pivot table with a MultiIndex on both the rows (Date, Product) and columns (City)?

In [152]:
df.pivot_table(index=["Product", "Date"], columns="City", values="Sales").fillna(0)

City                   Chicago  Dallas  Houston  Los Angeles  Miami  New York
Product    Date
Headphones 2024-02-02      0.0    16.0     17.0          0.0    0.0       0.0
           2024-02-03      0.0    16.0      0.0          7.5    0.0       0.0
           2024-02-06      0.0     0.0      7.0         18.0    0.0       0.0
Laptop     2024-02-01      0.0     0.0      0.0          0.0   11.0      14.5
           2024-02-04     20.5     0.0      0.0          0.0    0.0       9.5
           2024-02-07      9.5     0.0      0.0          0.0   12.0       0.0
Smartphone 2024-02-01     13.0     0.0      0.0          0.0   12.5      10.0
           2024-02-02      0.0     0.0      0.0          0.0    0.0      10.0
           2024-02-04      0.0     0.0      0.0          0.0    0.0      14.0
           2024-02-05      9.0     0.0      0.0          0.0    0.0      13.0
Smartwatch 2024-02-03      0.0    19.5     20.5         18.0    0.0       0.0
           2024-02-04      0.0     0.0      0.0         15.0    0.0       0.0
           2024-02-06      0.0     0.0      0.0         15.0    0.0       0.0
           2024-02-07      0.0     0.0     18.5         14.0    0.0       0.0
Tablet     2024-02-01      7.0     0.0      0.0          0.0    0.0       0.0
           2024-02-02      0.0     8.0      7.0         11.0    8.0      13.0
           2024-02-05     12.0     0.0      0.0          7.0    0.0       7.0
           2024-02-06      0.0     0.0     13.0          0.0    0.0       0.0

10. How can you add a total row and column to a pivot table showing Sales for each City on each Date?

In [153]:
df_pivot_1 = df.pivot_table(index="City", columns="Date", values="Sales", margins=True, margins_name="Total", aggfunc="sum").fillna(0)
df_pivot_1.columns = [col.strftime('%Y-%m-%d') if isinstance(col, pd.Timestamp) else col for col in df_pivot_1.columns]
df_pivot_1

,2024-02-01,2024-02-02,2024-02-03,2024-02-04,2024-02-05,2024-02-06,2024-02-07,Total
City,,,,,,,,
Chicago,33.0,0.0,0.0,41.0,30.0,0.0,19.0,123
Dallas,0.0,24.0,55.0,0.0,0.0,0.0,0.0,79
Houston,0.0,41.0,41.0,0.0,0.0,27.0,37.0,146
Los Angeles,0.0,11.0,33.0,15.0,7.0,51.0,14.0,131
Miami,36.0,8.0,0.0,0.0,0.0,0.0,12.0,56
New York,39.0,23.0,0.0,33.0,20.0,0.0,0.0,115
Total,108.0,107.0,129.0,89.0,57.0,78.0,82.0,650

In [154]:
data = {
    "City": [
        "New York", "New York", "New York", "New York", "New York", "Los Angeles", "Los Angeles", "Los Angeles", "Los Angeles", "Los Angeles",
        "Chicago", "Chicago", "Chicago", "Chicago", "Chicago", "Houston", "Houston", "Houston", "Houston", "Houston",
        "Miami", "Miami", "Miami", "Miami", "Miami", "Dallas", "Dallas", "Dallas", "Dallas", "Dallas",
        "New York", "New York", "New York", "New York", "New York", "Los Angeles", "Los Angeles", "Los Angeles", "Los Angeles", "Los Angeles",
        "Chicago", "Chicago", "Chicago", "Chicago", "Chicago", "Houston", "Houston", "Houston", "Houston", "Houston"
    ],
    "Date": pd.to_datetime([
        "2024-02-01", "2024-02-01", "2024-02-01", "2024-02-02", "2024-02-02", "2024-02-02", "2024-02-03", "2024-02-03", "2024-02-03", "2024-02-04",
        "2024-02-04", "2024-02-04", "2024-02-05", "2024-02-05", "2024-02-05", "2024-02-06", "2024-02-06", "2024-02-06", "2024-02-07", "2024-02-07",
        "2024-02-07", "2024-03-01", "2024-03-01", "2024-03-01", "2024-03-02", "2024-03-02", "2024-03-02", "2024-03-03", "2024-03-03", "2024-03-03",
        "2024-03-04", "2024-03-04", "2024-03-04", "2024-03-05", "2024-03-05", "2024-03-05", "2024-03-06", "2024-03-06", "2024-03-06", "2024-03-07",
        "2024-03-07", "2024-03-07", "2024-04-01", "2024-04-01", "2024-04-01", "2024-04-02", "2024-04-02", "2024-04-02", "2024-04-03", "2024-04-03"
    ]),
    "Product": [
        "Laptop", "Laptop", "Smartphone", "Smartphone", "Tablet", "Tablet", "Headphones", "Headphones", "Smartwatch", "Smartwatch",
        "Laptop", "Laptop", "Smartphone", "Smartphone", "Tablet", "Tablet", "Headphones", "Headphones", "Smartwatch", "Smartwatch",
        "Laptop", "Laptop", "Smartphone", "Smartphone", "Tablet", "Tablet", "Headphones", "Headphones", "Smartwatch", "Smartwatch",
        "Laptop", "Laptop", "Smartphone", "Smartphone", "Tablet", "Tablet", "Headphones", "Headphones", "Smartwatch", "Smartwatch",
        "Laptop", "Laptop", "Smartphone", "Smartphone", "Tablet", "Tablet", "Headphones", "Headphones", "Smartwatch", "Smartwatch"
    ],
    "Sales": [
        15, 14, 10, 10, 13, 11, 7, 8, 18, 15, 21, 20, 9, 9, 12, 13, 7, 7, 19, 18,12, 11, 13, 12, 8, 8, 16, 
        16, 20, 19, 9, 10, 14, 13, 7, 7, 18, 18, 15, 14, 10, 9, 13, 13, 7, 7, 18, 16, 21, 20
    ],
    "Profit": [
        30000, 28000, 12000, 14000, 25000, 20000, 9000, 10000, 40000, 35000, 50000, 48000, 13000, 15000, 27000, 25000, 8000, 9500,
        42000, 39000, 21000, 19000, 23000, 22000, 10000, 12000, 37000, 35000, 48000, 46000, 15000, 14000, 26000, 24000, 9500, 
        10000, 41000, 39000, 30000, 28000, 12000, 11000, 25000, 23000, 9000, 8500, 40000, 38000, 50000, 48000
    ]
}
df = pd.DataFrame(data)
print(df.head(10))

          City       Date     Product  Sales  Profit
0     New York 2024-02-01      Laptop     15   30000
1     New York 2024-02-01      Laptop     14   28000
2     New York 2024-02-01  Smartphone     10   12000
3     New York 2024-02-02  Smartphone     10   14000
4     New York 2024-02-02      Tablet     13   25000
5  Los Angeles 2024-02-02      Tablet     11   20000
6  Los Angeles 2024-02-03  Headphones      7    9000
7  Los Angeles 2024-02-03  Headphones      8   10000
8  Los Angeles 2024-02-03  Smartwatch     18   40000
9  Los Angeles 2024-02-04  Smartwatch     15   35000

11. How would you create a pivot table to show monthly Sales for each Product given the Date column includes multiple months?

In [120]:
df_pivot_2 = df.pivot_table(index="Product", columns="Date", values="Sales").fillna(0)
df_pivot_2.columns = [col.strftime("%B") if isinstance(col, pd.Timestamp) else col for col in df_pivot_2.columns]
df_pivot_2.groupby(axis=1, level=0).sum()

            April  February  March
Product
Headphones   17.0      14.5   50.0
Laptop        0.0      47.0   30.0
Smartphone   13.0      29.0   39.5
Smartwatch   20.5      51.5   48.5
Tablet       14.0      37.0   15.0

12. How would you pivot the DataFrame to compare the average Profit across different Cities?

In [124]:
df.pivot_table(index="City", values="Profit", aggfunc="mean")

             Profit
City
Chicago       23300
Dallas        35600
Houston       30800
Los Angeles   26200
Miami         19000
New York      19750

13. How can you create a pivot table to show the count of Sales transactions for each Product segmented by City?

In [ ]:
# The sales field is using the metric "units sold". We can use "sum", if the requirement is to get the number of total products sold.
df.pivot_table(index="City", columns="Product", values="Sales", aggfunc="count").fillna(0)

Product      Headphones  Laptop  Smartphone  Smartwatch  Tablet
City
Chicago             0.0     4.0         4.0         0.0     2.0
Dallas              2.0     0.0         0.0         2.0     1.0
Houston             4.0     0.0         0.0         4.0     2.0
Los Angeles         4.0     0.0         0.0         4.0     2.0
Miami               0.0     2.0         2.0         0.0     1.0
New York            0.0     4.0         4.0         0.0     2.0

14. How can you prepare the DataFrame for a heatmap visualization by pivoting City, Date, and Sales to have City as rows and Date as columns?

In [131]:
df_pivot_3 = df.pivot_table(index="City", columns="Date", values="Sales", aggfunc="sum").fillna(0)
df_pivot_3.index.name = None
df_pivot_3.columns.name = None
df_pivot_3

,2024-02-01,2024-02-02,2024-02-03,2024-02-04,2024-02-05,2024-02-06,2024-02-07,2024-03-01,2024-03-02,2024-03-03,2024-03-04,2024-03-05,2024-03-06,2024-03-07,2024-04-01,2024-04-02,2024-04-03
Chicago,0.0,0.0,0.0,41.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0,33.0,0.0,0.0
Dallas,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,55.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Houston,0.0,0.0,0.0,0.0,0.0,27.0,37.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.0,41.0
Los Angeles,0.0,11.0,33.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,51.0,14.0,0.0,0.0,0.0
Miami,0.0,0.0,0.0,0.0,0.0,0.0,12.0,36.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
New York,39.0,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33.0,20.0,0.0,0.0,0.0,0.0,0.0

15. How can you use a custom aggregation function (e.g., lambda x: x.max() - x.min()) in a pivot table to calculate the range of Sales for each Product in each
City?

In [ ]:
df.pivot_table(index="City", columns="Product", values="Sales", aggfunc=lambda x:x.max()-x.min()).fillna(0)

Product      Headphones  Laptop  Smartphone  Smartwatch  Tablet
City
Chicago             0.0    12.0         4.0         0.0     5.0
Dallas              0.0     0.0         0.0         1.0     0.0
Houston            11.0     0.0         0.0         3.0     6.0
Los Angeles        11.0     0.0         0.0         4.0     4.0
Miami               0.0     1.0         1.0         0.0     0.0
New York            0.0     6.0         4.0         0.0     6.0